### ISSUE TITLE
Run format

### ISSUE THREAD

**Issue by pfletch1** [TheColorRed/vscode-format#1]
Hi, I am new to VS Code and installed your Visual Studio Code Format plugin, how do I actually format the code?

**Comment by TheColorRed** [comment]
Vscode has a command to format the code. If you open your user preferences, `File->Preferences->Keyboard Shortcuts` it will open `Default Keyboard Shortcuts` In there you will find this key combination:

``` json
{ 
    "key": "shift+alt+f",           
    "command": "editor.action.format",
    "when": "editorTextFocus" 
}
```

Running this command will format your document. If you changed the command to something else run that command instead.
